cms/controllers/PageController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Categories;
use app\models\Products;
use app\models\SortForm;
use app\models\Characteristics;
use yii\web\NotAcceptableHttpException;
/*Контроллер для страниц сайта*/
class PageController extends Controller
{
   

    /**
       Для страницы списка товаров
     */
    public function actionListproducts()
    {
        if(isset($_GET['ID']) && $_GET['ID']!="" && filter_var($_GET['ID'],FILTER_VALIDATE_INT))
        {
            //ID категории
            $ID = $_GET['ID'];


            $categories = Categories::find()->where(['ID'=> $ID])->asArray()->one();

            $characteristics = Characteristics::find()->where(['name'=> $IDprod])->asArray()->one();

            if(count($categories) > 0)
           {  
              $model = new SortForm();

              $count_products = count(Products::find()->where(['category' => $ID])->asArray()->all());

              $page = 1; // номер страницы
              $str = null; //сортировка
              $number = 12; //кол-во товаров на странице

              if(isset($_GET['page']) && $_GET['page']!="" && filter_var($_GET['page'],FILTER_VALIDATE_INT))
              {
                $page = $_GET['page'];
              }

              // обработчик для формы сортировки
              if ($model->load(Yii::$app->request->post()) && $model->validate())
              {

                if(isset($model->number) && !empty($model->number)){
                    $number = $model->number;
                }
           
                if(isset($model->str)){

                    switch ($model->str) {
                        case 0:
                            $products_array = $this->selectListProd($ID, ['price'=> SORT_ASC], $number, $page);
                           break;
                        case 1:
                             $products_array = $this->selectListProd($ID, ['price'=> SORT_DESC], $number, $page);
                           break;
                        case 2:
                            $products_array = $this->selectListProd($ID, ['name'=> SORT_ASC], $number, $page);
                           break;
                        case 3:
                            $products_array = $this->selectListProd($ID, ['name'=> SORT_DESC], $number, $page);
                           break;
                        default:
                            $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
                           break;

                    }
                }
                else{
                    $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
                }

             }

             else {
                $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
              }

              //кол-во страниц для пагинации
              $count_pages = ceil($count_products / $number);
              

              if(isset($_GET['view']) && $_GET['view'] == 1)
                $view = 1;
            else
                $view = 0;

              return $this->render('listproducts', compact('categories','products_array','count_products','view','model','count_pages','ID', 'characteristics'));
            }

        }
            return $this->redirect(['page/catalog']);

            
        }
       
        private function selectListProd($ID, $field_sort, $limit, $start){

            if($start == 1)
                $start = 0;
            else
                $start = ($start - 1) * $limit;

                return Products::find()->where(['category' => $ID])->asArray()->orderBy($field_sort)->limit($limit)->offset($start)->all();
    }

        /**
       Для страницы каталога
     */
    public function actionCatalog()
    {
 
        $categories = Categories::find()->asArray()->all();
        
        return $this->render('catalog',compact('categories'));
    }

            /**
       Для страницы каталога
     */
    public function actionProduct()
    {
 
       $this->layout = "product";
      
      if(isset($_GET['ID']) && !empty($_GET['ID']) && filter_var($_GET['ID'], FILTER_VALIDATE_INT)){
            $ID = $_GET['ID'];
        }
        else{
            throw new NotAcceptableHttpException;
        }

        $product_array = Products::find()->where(['ID' => $ID])->asArray()->one();
        if(!is_array($product_array) || count($product_array) < 0){
            throw new NotAcceptableHttpException;
        }


        return $this->render('product', compact('product_array', 'ID'));
    }


     /**
       Для страницы новостей
     */
    public function actionNews()
    {

        return $this->render('news');
    }

  /**
       Для страницы контакты
     */
    public function actionContacts()
    {

        return $this->render('contacts');
    }

  /**
       Для страницы войти
     */
    public function actionLogin()
    {

        return $this->render('login');
    }

/**
       Для страницы обратная связь
     */
    public function actionConnection()
    {

        return $this->render('connection');
    }
/**
       Для страницы личный кабинет
     */
    public function actionCabinet()
    {

        return $this->render('cabinet');
    }
/**
     	Для страницы Доставка
     */
    public function actionDostavka()
    {
        return $this->render('dostavka');
    }

    /**
     	Для страницы Оплата
     */
    public function actionOplata()
    {
        return $this->render('oplata');
    }

    /**
     	Для страницы О компании
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     	Для страницы Скидки
     */
    public function actionSale()
    {
        return $this->render('sale');
    }

    /**
     	Для страницы Карта сайта
     */
    public function actionSitemap()
    {
        return $this->render('sitemap');
    }

    /**
     	Для страницы корзина
     */
    public function actionCart()
    {
        return $this->render('cart');
    }

    /**
     	Для страницы Список желаний
     */
    public function actionListorder()
    {
        return $this->render('listorder');
    }

 /**
     	Для страницы зарегистрироваться
     */
    public function actionRegistration()
    {
        return $this->render('registration');
    }

}

cms/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
    	$this->layout = 'main';
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

cms/views/layouts/default.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\DefaultAsset;
use yii\helpers\Url;

DefaultAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <header>
      <div class="container">
        <div class="row header_top">
          <div class="logo col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <a href="/"><img src="images/logo.png"></a>
          </div>
          <div class="btn_top_wrap col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="btn_and_search">
              <div class="btn_top">
                <a href="<?=Url::toRoute('page/connection');?>"><i class="glyphicon glyphicon-map-marker"></i>Обратная связь</a>
                <a href="<?=Url::toRoute('page/cabinet');?>"><i class="glyphicon glyphicon-user"></i>Личный кабинет</a>
                <a href="<?=Url::toRoute('page/login');?>"><i class="glyphicon glyphicon-lock"></i>Войти</a>
              </div>
              <div class="search_top">
                <form>
                    <input placeholder="Поиск" type="text">
                    <button type="submit" name="submit_search">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                </form>
              </div>
            </div>
            <div class="cart_top">
              <a href="#">
                <i class="glyphicon glyphicon-shopping-cart"></i>
                <span>0</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="container-fluid menu_top">
        <div class="container">
          <div class="row">


                <?php


                        NavBar::begin([

                            'brandUrl' => Yii::$app->homeUrl,
                            'options' => [
                                'class' => ' ',
                            ],
                        ]);
                        echo Nav::widget([
                            'options' => ['class' => 'navbar-nav '],
                            'items' => [
                               ['label' => 'Главная', 'url' => ['/site/index']],
					            ['label' => 'Каталог', 'url' => ['/page/catalog']],
					            ['label' => 'Контакты', 'url' => ['/page/contacts']],
					            ['label' => 'Новости', 'url' => ['/site/news']],
                            ],
                        ]);
                        NavBar::end();

                        ?>
          </div>
        </div>
      </div>
  </header>

    <div class="container">
        <div class="row">
            <div class="col-lg-12 contant_wrap">
                <div class="navigation">
                    <ul>
                        <li><a href="#"><i class="glyphicon glyphicon-home"></i></a></li>
                        <li><a href="#">Снаряжение</a></li>
                        <li><span>Рюкзаки</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            
            


          <?=$content;?>

        </div>
    </div>

    <div class="container-fluid write_email_and_sseti">
      <div class="container">
        <div class="row write_email_and_sseti_wrap">
          <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12 write_email">
            <p>Рассылка</p>
            <form>
              <button type="submit">
                      <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
              <input type="text" placeholder="Введите E-mail">
            </form>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-5 hidden-xs sseti_wrap">
            <div>
              <a href="#"><i class="fa fa-facebook"></i></a>
              <a href="#"><i class="fa fa-vk"></i></a>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid footer">
      <div class="container">
        <div class="row menu_footer_and_contact">
          <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
            <div class="footer_menu">
              <h3>Категории</h3>
              <ul>
                <li><a href="#">Смартфоны</a></li>
                <li><a href="#">Кнопочные телефоны</a></li>
                <li><a href="#">Портативная электроника</a></li>
                <li><a href="#">Аксессуары</a></li>
              </ul>
            </div>
            <div class="footer_menu">
              <h3>Информация</h3>
              <ul>
                <li><a href="<?=Url::toRoute('page/dostavka');?>">Доставка</a></li>
                <li><a href="<?=Url::toRoute('page/oplata');?>">Оплата</a></li>
                <li><a href="<?=Url::toRoute('page/about');?>">О компании</a></li>
                <li><a href="<?=Url::toRoute('page/sale');?>">Скидки</a></li>
                <li><a href="<?=Url::toRoute('page/sitemap');?>">Карта сайта</a></li>
              </ul>
            </div>
            <div class="footer_menu">
              <h3>Учетная запись</h3>
              <ul>
                <li><a href="<?=Url::toRoute('page/login');?>">Войти</a></li>
                <li><a href="<?=Url::toRoute('page/registration');?>">Зарегистрироваться</a></li>
                <li><a href="<?=Url::toRoute('page/cart');?>">Мои заказы</a></li>
                <li><a href="<?=Url::toRoute('page/listorder');?>">Список желаний</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 contacts">
            <h3>Контакты</h3>
            <p><i class="glyphicon glyphicon-map-marker"></i>Адрес: ул. Ленина, 9 г. Москва, 603089</p>
            <p><i class="glyphicon glyphicon-phone-alt"></i>Служба поддержки: 8 (800) 000-00-00</p>
            <p><i class="glyphicon glyphicon-envelope"></i>E-mail: info@myshop.ru</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 copy">
            <p>© 2020 не является действующим интернет-магазином</p>
          </div>
        </div>
      </div>
    </div>










    <?php
/*
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
 */
    ?>

  
        <?/*= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ])*/ ?>
        <?= Alert::widget() ?>
        <?//= $content ?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

cms/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <header>
      <div class="container">
        <div class="row header_top">
          <div class="logo col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <a href="/"><img src="images/logo.png"></a>
          </div>
          <div class="btn_top_wrap col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="btn_and_search">
              <div class="btn_top">
                <a href="<?=Url::toRoute('page/connection')?>"><i class="glyphicon glyphicon-map-marker"></i>Обратная связь</a>
                <a href="<?=Url::toRoute('page/cabinet')?>"><i class="glyphicon glyphicon-user"></i>Личный кабинет</a>
                <a href="<?=Url::toRoute('page/login')?>"><i class="glyphicon glyphicon-lock"></i>Войти</a>
              </div>
              <div class="search_top">
                <form>
                    <input placeholder="Поиск" type="text">
                    <button type="submit" name="submit_search">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                </form>
              </div>
            </div>
            <div class="cart_top">
              <a href="#">
                <i class="glyphicon glyphicon-shopping-cart"></i>
                <span>0</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="container-fluid menu_top">
        <div class="container">
          <div class="row">


              	<?php


					    NavBar::begin([

					        'brandUrl' => Yii::$app->homeUrl,
					        'options' => [
					            'class' => ' ',
					        ],
					    ]);
					   echo Nav::widget([
					      'options' => ['class' => 'navbar-nav '],
					       'items' => [
					        ['label' => 'Главная', 'url' => ['/site/index']],
					        ['label' => 'Каталог', 'url' => ['/page/catalog']],
					        ['label' => 'Контакты', 'url' => ['/page/contacts']],
					        ['label' => 'Новости', 'url' => ['/site/news']],
					          
					        ],
					    ]);
					    NavBar::end();

					    ?>
<!--
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                  </div>

                 
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="#">Смартфоны</a></li>
                      <li><a href="#">Телефоны с кнопками</a></li>
                      <li><a href="#">Портативная электроника</a></li>
                      <li><a href="#">Аксессуары</a></li>
                    </ul>
                  </div>
-->
          </div>
        </div>
      </div>
    </header>


    <div class="container ban_block_wrap">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ban_block ban1">
          <div>
            <img src="images/ban1.jpg">
            <a href="#">
              <h2>Apple</h2>
              <p>Широкий выбор техники Apple</p>
              <span>Подробнее</span>
            </a>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ban_block">
          <div>
            <img src="images/ban2.jpg">
            <a href="#">
              <h2>Samsung</h2>
              <p>Широкий выбор техники Samsung</p>
              <span>Подробнее</span>
            </a>
          </div>
        </div>
      </div>
    </div>

    <?=$content;?>

    <div class="container-fluid write_email_and_sseti">
        <div class="container">
            <div class="row write_email_and_sseti_wrap">
                <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12 write_email">
                    <p>Рассылка</p>
                    <form>
                        <button type="submit">
                          <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                        <input type="text" placeholder="Введите E-mail">
                    </form>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-5 hidden-xs sseti_wrap">
                    <div>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-vk"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid footer">
        <div class="container">
            <div class="row menu_footer_and_contact">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="footer_menu">
                        <h3>Категории</h3>
                        <ul>
                            <li><a href="#">Смартфоны</a></li>
                            <li><a href="#">Кнопочные телефоны</a></li>
                            <li><a href="#">Портативная электроника</a></li>
                            <li><a href="#">Аксессуары</a></li>
                        </ul>
                    </div>
                    <div class="footer_menu">
                        <h3>Информация</h3>
                        <ul>
                           <li><a href="<?=Url::toRoute('page/dostavka');?>">Доставка</a></li>
                            <li><a href="<?=Url::toRoute('page/oplata');?>">Оплата</a></li>
                            <li><a href="<?=Url::toRoute('page/about');?>">О компании</a></li>
                            <li><a href="<?=Url::toRoute('page/sale');?>">Скидки</a></li>
                            <li><a href="<?=Url::toRoute('page/sitemap');?>">Карта сайта</a></li>
                        </ul>
                    </div>
                    <div class="footer_menu">
                        <h3>Учетная запись</h3>
                        <ul>
                            <li><a href="<?=Url::toRoute('page/login');?>">Войти</a></li>
                            <li><a href="<?=Url::toRoute('page/registration');?>">Зарегистрироваться</a></li>
                            <li><a href="<?=Url::toRoute('page/cart');?>">Мои заказы</a></li>
                            <li><a href="<?=Url::toRoute('page/listorder');?>">Список желаний</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 contacts">
                    <h3>Контакты</h3>
                    <p><i class="glyphicon glyphicon-map-marker"></i>Адрес: ул. Ленина, 9 г. Москва, 603089</p>
                    <p><i class="glyphicon glyphicon-phone-alt"></i>Служба поддержки: 8 (800) 000-00-00</p>
                    <p><i class="glyphicon glyphicon-envelope"></i>E-mail: info@myshop.ru</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 copy">
                    <p>© 2020 не является действующим интернет-магазином</p>
                </div>
            </div>
        </div>
    </div>











    <?php
/*
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
 */
    ?>

  
        <?/*= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ])*/ ?>
        <?= Alert::widget() ?>
        <?//= $content ?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>