cms/controllers/PageController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Categories;
use app\models\Products;
use app\models\SortForm;
use app\models\Characteristics;
use yii\web\NotAcceptableHttpException;
/*Контроллер для страниц сайта*/
class PageController extends Controller
{
   

    /**
       Для страницы списка товаров
     */
    public function actionListproducts()
    {
        if(isset($_GET['ID']) && $_GET['ID']!="" && filter_var($_GET['ID'],FILTER_VALIDATE_INT))
        {
            //ID категории
            $ID = $_GET['ID'];


            $categories = Categories::find()->where(['ID'=> $ID])->asArray()->one();

            $characteristics = Characteristics::find()->where(['name'=> $IDprod])->asArray()->one();

            if(count($categories) > 0)
           {  
              $model = new SortForm();

              $count_products = count(Products::find()->where(['category' => $ID])->asArray()->all());

              $page = 1; // номер страницы
              $str = null; //сортировка
              $number = 12; //кол-во товаров на странице

              if(isset($_GET['page']) && $_GET['page']!="" && filter_var($_GET['page'],FILTER_VALIDATE_INT))
              {
                $page = $_GET['page'];
              }

              // обработчик для формы сортировки
              if ($model->load(Yii::$app->request->post()) && $model->validate())
              {

                if(isset($model->number) && !empty($model->number)){
                    $number = $model->number;
                }
           
                if(isset($model->str)){

                    switch ($model->str) {
                        case 0:
                            $products_array = $this->selectListProd($ID, ['price'=> SORT_ASC], $number, $page);
                           break;
                        case 1:
                             $products_array = $this->selectListProd($ID, ['price'=> SORT_DESC], $number, $page);
                           break;
                        case 2:
                            $products_array = $this->selectListProd($ID, ['name'=> SORT_ASC], $number, $page);
                           break;
                        case 3:
                            $products_array = $this->selectListProd($ID, ['name'=> SORT_DESC], $number, $page);
                           break;
                        default:
                            $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
                           break;

                    }
                }
                else{
                    $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
                }

             }

             else {
                $products_array = $this->selectListProd($ID, ['ID'=> SORT_ASC], $number, $page);
              }

              //кол-во страниц для пагинации
              $count_pages = ceil($count_products / $number);
              

              if(isset($_GET['view']) && $_GET['view'] == 1)
                $view = 1;
            else
                $view = 0;

              return $this->render('listproducts', compact('categories','products_array','count_products','view','model','count_pages','ID', 'characteristics'));
            }

        }
            return $this->redirect(['page/catalog']);

            
        }
       
        private function selectListProd($ID, $field_sort, $limit, $start){

            if($start == 1)
                $start = 0;
            else
                $start = ($start - 1) * $limit;

                return Products::find()->where(['category' => $ID])->asArray()->orderBy($field_sort)->limit($limit)->offset($start)->all();
    }

        /**
       Для страницы каталога
     */
    public function actionCatalog()
    {
 
        $categories = Categories::find()->asArray()->all();
        
        return $this->render('catalog',compact('categories'));
    }

            /**
       Для страницы каталога
     */
    public function actionProduct()
    {
 
       $this->layout = "product";
      
      if(isset($_GET['ID']) && !empty($_GET['ID']) && filter_var($_GET['ID'], FILTER_VALIDATE_INT)){
            $ID = $_GET['ID'];
        }
        else{
            throw new NotAcceptableHttpException;
        }

        $product_array = Products::find()->where(['ID' => $ID])->asArray()->one();
        if(!is_array($product_array) || count($product_array) < 0){
            throw new NotAcceptableHttpException;
        }


        return $this->render('product', compact('product_array', 'ID'));
    }


     /**
       Для страницы новостей
     */
    public function actionNews()
    {

        return $this->render('news');
    }

  /**
       Для страницы контакты
     */
    public function actionContacts()
    {

        return $this->render('contacts');
    }

  /**
       Для страницы войти
     */
    public function actionLogin()
    {

        return $this->render('login');
    }

/**
       Для страницы обратная связь
     */
    public function actionConnection()
    {

        return $this->render('connection');
    }
/**
       Для страницы личный кабинет
     */
    public function actionCabinet()
    {

        return $this->render('cabinet');
    }
/**
     	Для страницы Доставка
     */
    public function actionDostavka()
    {
        return $this->render('dostavka');
    }

    /**
     	Для страницы Оплата
     */
    public function actionOplata()
    {
        return $this->render('oplata');
    }

    /**
     	Для страницы О компании
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     	Для страницы Скидки
     */
    public function actionSale()
    {
        return $this->render('sale');
    }

    /**
     	Для страницы Карта сайта
     */
    public function actionSitemap()
    {
        return $this->render('sitemap');
    }

    /**
     	Для страницы корзина
     */
    public function actionCart()
    {
        return $this->render('cart');
    }

    /**
     	Для страницы Список желаний
     */
    public function actionListorder()
    {
        return $this->render('listorder');
    }

 /**
     	Для страницы зарегистрироваться
     */
    public function actionRegistration()
    {
        return $this->render('registration');
    }

}

cms/views/page/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

cms/views/page/cabinet.php
Вход в личный кабинет

cms/views/page/cart.php
      <?php

use yii\helpers\Url;

$this->title = 'Корзина';
?>

      <div class="row cart_wrap">
        <div class="col-lg-12 top_cart_block">
          <div>
            <p>Состояние корзины</p>
            <p>Ваша корзина содержит: 1 товар</p>
          </div>
        </div>
        <div class="col-lg-12">
          <ul class="cart_status">
            <li class="active"><span>1. Заказ</span></li>
            <li><span>2. Адрес</span></li>
            <li><span>3. Доставка</span></li>
            <li><span>4. Оплата</span></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <table class="table table-bordered">
            <tr class="cart_prod_head">
              <td class="img_cart">Товар</td>
              <td class="title_cart">Описание</td>
              <td class="price_cart">Цена за единицу</td>
              <td class="value_cart">Кол-во</td>
              <td class="rez_price_cart">Стоимость</td>
            </tr>
            <tr class="cart_prod_content">
              <td class="img_cart"><img src="images/prod1.jpg"></td>
              <td class="title_cart">Рюкзак туристический</td>
              <td class="price_cart">3500 руб</td>
              <td class="value_cart">
                <div>
                  <input type="text" value="1">
                  <span>-</span>
                  <span>+</span>
                </div>
              </td>
              <td class="rez_price_cart">3500 руб</td>
            </tr>
            <tr class="cart_prod_footer">
              <td colspan="2" class="null_cart"></td>
              <td colspan="2" class="rez_title_cart">Итого, к оплате:</td>
              <td class="rez_price_cart">3500 руб</td>
            </tr>
          </table>
          </div>
          <div class="col-lg-12 btn_cart_wrap">
            <a href="#" class="btn_cart_im"><i class="glyphicon glyphicon-chevron-left"></i>Продолжить покупки</a>
            <a href="#" class="btn_cart_zakaz">Оформить заказ<i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>

cms/views/page/catalog.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = 'Каталог';
?>


   <div class="col-lg-3 col-md-3 col-sm-5 col-xs-12 left_banner_menu">
                  баннерное меню     
            </div>


   <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 catalog">
          <div class="row content">

          	<?php foreach ($categories as $category):?>
				<div class="col-lg-4 col-md-6 col-sm-4 col-xs-12 catalog_category">
              	 <a href="<?=Url::toRoute(['page/listproducts','ID'=>$category['ID']]);?>"><img src="images/<?php echo $category['img'];?>"></a>
              	 <a href="<?=Url::toRoute(['page/listproducts','ID'=>$category['ID']]);?>"><?php echo $category['name'];?></a>
              </div>  
          	<?php endforeach;?>
              
            </div>              
          </div>

cms/views/page/connection.php
Обратная связь

cms/views/page/contacts.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

cms/views/page/dostavka.php
доставка

cms/views/page/listorder.php
список желаний

cms/views/page/listproducts.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = "Интернет-магазин | ".$categories['name'];

$this->registerMetaTag(['name' => 'keywords', 'content' => 'сотовые телефоны, аксессуары']);
$this->registerMetaTag(['name' => 'description', 'content' => 'смартфоны для всей семьи']);
?>

   <div class="col-lg-3 col-md-3 col-sm-5 col-xs-12 filter">
                <h3>Фильтры</h3>
                <form>
                    <label>Цена / руб</label>
            <div class="filter_price">
              <input type="text" value="0">
              -
              <input type="text" value="10000">
            </div>
                    <label>Объем / л</label>
            <div class="filter_check">
              <p><input type="checkbox"/>10</p>
              <p><input type="checkbox"/>20</p>
              <p><input type="checkbox"/>30</p>
            </div>

                    <button type="submit">Подобрать</button>
                </form>
            </div>



   <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
         <div class="short_description">
                    <img src="images/<?php echo $categories['img'];?>">
                    <div>
                        <h2><?php echo $categories['name'];?></h2>
                        <p><?php echo $categories['description'];?></p>
                    </div>
                </div>
          <div class="row content">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 header_list_prod">
                <div class="row">
                  <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h1><?php echo $categories['name']?></h1>
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 value_prod">
                    <p>В наличии: <?=$count_products;?></p>
                  </div>
                </div>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 sortirovka_and_number_prod">
                    
                 <?php $form = ActiveForm::begin();?>  
              <p><strong>Сортировка по:</strong><?= $form->field($model, 'str')->dropDownList([
                                                              '0' => 'Цене, по возрастанию', 
                                                              '1' => 'Цене, по убыванию', 
                                                              '2' => 'Названию товара, от А до Я', 
                                                              '3' => 'Названию товара, от Я до А'],
                                    $params = [
                                        'prompt' => '--',
                                    ]
              );?></p>
              <p><strong>Показать:</strong><?= $form->field($model, 'number')->dropDownList(['12' => '12', '24' => '24', '48' => '48'], $params = [
                                      'options' => ['12' => ['Selected' => true]],
                                    ]
              );?></p>
              <?= Html::submitButton('Применить');?>
              <?php ActiveForm::end(); ?>

                  </div>
                  <div class="col-lg-3 col-md-3 col-sm-3 hidden-xs view_list_prod">
                    <p><strong>Вид:</strong>
                    <?php 
                      if ($view == 1)
                          $class2 = "active";
                        else
                          $class1 = "active";
                        ?>

                      <a href="<?=Url::toRoute(['page/listproducts','ID'=> $categories['ID']]);?>" class="<?=$class1;?>"><i class="glyphicon glyphicon-th"></i><span>Сетка</span></a>

                      <a href="<?=Url::toRoute(['page/listproducts','ID'=> $categories['ID'],'view'=>'1']);?>" class="<?=$class2;?>"><i class="glyphicon glyphicon-th-list"></i><span>Список</span></a>
                    </p>
                  </div>
                </div>
              </div>

              <?php 

              foreach ($products_array as $product_array):?>
                <?php if($view == 1):?>
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 view_list">
                <div class="product">
                  <a href="<?=Url::toRoute(['page/product','ID'=> $product_array['ID']]);?>" class="product_img">
                    <?php if ($product_array['price_old'] != ""):?> 
                    <span>-<?php echo 100-intval($product_array['price']*100/$product_array['price_old']);?>%</span>
                    
                    <?php endif?>
                    <img src="images/<?=$product_array['img'];?>">
                  </a>
                  <div class="desc">
                  <a href="<?=Url::toRoute(['page/product','ID'=>$product_array['ID']]);?>" class="product_title"><?=$product_array['name'];?></a>
                  <div class="product_price">
                    <span class="price"><?=$product_array['price']?> руб</span>
                    <?php if ($product_array['price_old'] != ""):?>
                    <span class="price_old"><?=$product_array['price_old']?> руб</span>
                  <?php endif;?>
                  </div>

                  <div class="desc_prod">
                    <table class="table table-striped table-bordered">
                      <tr>
                        <td>Экран, Пикс</td>
                        <td>6.1"/1792x828</td>
                      </tr>
                      <tr>
                        <td>Оперативная память, Гб</td>
                        <td>128</td>
                      </tr>
                      <tr>
                        <td>Основная камера, МПикс</td>
                        <td>12/12</td>
                      </tr>
                    </table>
                  </div>

                  <div class="product_btn">
                    <a href="<?=Url::toRoute(['page/cart','ID'=>$product_array['ID']]);?>" class="cart"><i class="glyphicon glyphicon-shopping-cart"></i></a>
                    <a href="<?=Url::toRoute(['page/listorder','ID'=>$product_array['ID']]);?>" class="mylist">Список желаний</a>
                  </div>
                </div>
              </div> 
              </div>                   
                    <?php else:?>

                      <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12">
                <div class="product">
                  <a href="<?=Url::toRoute(['page/product','ID'=> $product_array['ID']]);?>" class="product_img">
                    <?php if ($product_array['price_old'] != ""):?> 
                    <span>-<?php echo 100-intval($product_array['price']*100/$product_array['price_old']);?>%</span>
                    
                    <?php endif;?>
                    <img src="images/<?=$product_array['img'];?>">
                  </a>
                  <div class="desc">
                  <a href="<?=Url::toRoute(['page/product','ID'=>$product_array['ID']]);?>" class="product_title"><?=$product_array['name'];?></a>
                  <div class="product_price">
                    <span class="price"><?=$product_array['price']?> руб</span>
                    <?php if ($product_array['price_old'] != ""):?>
                    <span class="price_old"><?=$product_array['price_old']?> руб</span>
                  <?php endif;?>
                  </div>

                  <div class="product_btn">
                    <a href="<?=Url::toRoute(['page/cart','ID'=>$product_array['ID']]);?>" class="cart"><i class="glyphicon glyphicon-shopping-cart"></i></a>
                    <a href="<?=Url::toRoute(['page/listorder','ID'=>$product_array['ID']]);?>" class="mylist">Список желаний</a>
                  </div>
                </div>
              </div>
            </div>
          <?php endif;?>
          <?php endforeach;?>

          </div>
          <div class="row pagination"> 

          <?php 
            if(isset($count_pages) && $count_pages > 1){
          ?>
            <ul>
              <?php 
                for($i = 1; $i <= $count_pages; $i++) {
              ?>
              <?php
                  if((!isset($_GET['page']) && $i ==1) || $_GET['page'] == $i) {?>

                    <li class="active"><span><?php echo $i;?></span></li>
              <?php } else { ?>

              <?php if(isset($_GET['view']) && $_GET['view'] == 1){?>  
                <li><a href="<?=Url::toRoute(['page/listproducts','ID'=>$ID, 'page' => $i, 'view' => 1]);?>"><?php echo $i;?></a></li>
              <?php } else { ?>  
                <li><a href="<?=Url::toRoute(['page/listproducts','ID'=>$ID, 'page' => $i]);?>"><?php echo $i;?></a></li>

              <?php }?>
              <?php }?>
              <?php 
            }
              ?>
            </ul> 
          <?php
            }  
          ?>    
         </div>

</div>

cms/views/page/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

cms/views/page/news.php
новости

cms/views/page/oplata.php
оплата

cms/views/page/product.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = 'Карточка товара';
?>

<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
    <div class="img_prod">
        <img src="images/<?php echo $product_array['img'];?>">
    </div>
</div>

<div class="col-lg-5 col-md-8 col-sm-7 col-xs-12">
    <div class="content_prod">
        <h1><?php echo $product_array['name'];?></h1>
        <p><span>Артикул:</span> <?php echo $product_array['code'];?></p>

        <?php
            if($product_array['count'] > 0):
        ?>
            <p>В наличии <strong class="count_prod"><?php echo $product_array['count'];?></strong></p>
        <?php
            else:
        ?>
                <p>Нет в наличии</p>
        <?php
            endif;
        ?>
        <p><?php echo $product_array['description'];?></p>
    </div>
</div>

<div class="col-lg-3 col-md-8 col-sm-7 col-sm-offset--5 col-xs-12">
    <div class="order_prod">
        <p class="price_prod"><?php echo $product_array['price'];?> руб</p>

        <?php
            if(!empty($product_array['price_old'])):
        ?>
            <p class="price_old_prod"><?php echo $product_array['price_old'];?> руб</p>
        <?php
            endif;
        ?>

        <?php
            $class = "";
            if($product_array['count'] > 0):
        ?>
        <p>Количество:</p>
        <form class="form_count_prod">
            <input type="text" name="" value="1" class="input_text">
            <button type="button" class="minus">-</button>
            <button type="button" class="plus">+</button>
        </form>
        <?php
            else:
            $class = "disabled";
        ?>
            <p>Нет в наличии</p>
        <?php
            endif;
        ?>
        <a href="<?=Url::toRoute('page/cart');?>" class="add_cart_prod <?php echo $class;?>"><i class="glyphicon glyphicon-shopping-cart"></i> В корзину</a>
        <a href="#" class="add_mylist_prod <?php echo $class;?>"><i class="glyphicon glyphicon-heart"></i>В список желаний</a>
    </div>
</div>

<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
    <div class="h_prod">
        <h3>Характеристики:</h3>
        <table class="table table-striped table-bordered">
            <tr>
                <td><?php echo $characteristics['name'];?></td>
                <td>6.1"/1792x828</td>
            </tr>
            <tr>
                <td>Оперативная память, Гб</td>
                <td>128</td>
            </tr>
            <tr>
                <td>Основная камера, МПикс</td>
                <td>12/12</td>
            </tr>
        </table>

    </div>
    <div class="r_prod">
        <h3>Отзывы:</h3>
        <div class="reviews">
            <div class="reviews_img">
                <img src="images/avatar.png">
            </div>
            <div class="reviews_contant">
                <p class="reviews_title">Иван <span>9.06.2017</span></p>
                <div class="reviews_rating">
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star no_active"></i>
                </div>
                <p class="reviews_text">Хороший рюкзак, рекомендую</p>
            </div>
        </div>
        <div class="reviews">
            <div class="reviews_img">
                <img src="images/avatar.png">
            </div>
            <div class="reviews_contant">
                <p class="reviews_title">Иван <span>9.06.2017</span></p>
                <div class="reviews_rating">
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star active"></i>
                    <i class="glyphicon glyphicon-star no_active"></i>
                </div>
                <p class="reviews_text">Хороший рюкзак, рекомендую</p>
            </div>
        </div>
        <div class="reviews_form">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <p>Отзыв о товаре:</p>
            </div>
            <form action="/" method="post">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="name" placeholder="Имя">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="email" placeholder="E-mail">
                </div>
                <div class="col-lg-12">
                    <textarea name="text" placeholder="Отзыв"></textarea>
                </div>
                <div class="col-lg-12">
                    <i class="glyphicon glyphicon-star"></i>
                    <i class="glyphicon glyphicon-star"></i>
                    <i class="glyphicon glyphicon-star"></i>
                    <i class="glyphicon glyphicon-star"></i>
                    <i class="glyphicon glyphicon-star"></i>
                </div>
                <div class="col-lg-12">
                    <button>Добавить</button>
                </div>
            </form>
        </div>
    </div>
</div>

cms/views/page/sale.php
скидки